-- Run once in Supabase SQL Editor before deploying the matching app.py update.

ALTER TABLE games ADD COLUMN IF NOT EXISTS away_team_id INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_team_id INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_team_name TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_team_name TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_lineup_status TEXT DEFAULT 'Pending';
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_lineup_status TEXT DEFAULT 'Pending';
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_lineup_json TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_lineup_json TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_injury_count INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_injury_count INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_injured_hitters INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_injured_hitters INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_injuries_json TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_injuries_json TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_bullpen_pitches_1d INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_bullpen_pitches_1d INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_bullpen_pitches_3d INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_bullpen_pitches_3d INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_bullpen_status TEXT DEFAULT 'Unknown';
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_bullpen_status TEXT DEFAULT 'Unknown';
ALTER TABLE games ADD COLUMN IF NOT EXISTS pitcher_change_detected BOOLEAN DEFAULT FALSE;
ALTER TABLE games ADD COLUMN IF NOT EXISTS pitcher_change_details TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS weather_risk_level TEXT DEFAULT 'Unknown';
ALTER TABLE games ADD COLUMN IF NOT EXISTS context_updated_at TIMESTAMPTZ;

ALTER TABLE model_recommendations ADD COLUMN IF NOT EXISTS model_version TEXT;
ALTER TABLE model_recommendations ADD COLUMN IF NOT EXISTS model_probability DOUBLE PRECISION;
ALTER TABLE model_recommendations ADD COLUMN IF NOT EXISTS rule_profile TEXT;
ALTER TABLE model_recommendations ADD COLUMN IF NOT EXISTS rule_checks_json TEXT;

CREATE TABLE IF NOT EXISTS model_prediction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(game_id), run_date TEXT NOT NULL,
    model_version TEXT NOT NULL, model_probability DOUBLE PRECISION,
    recommended_side TEXT, fair_line INTEGER, market_line INTEGER,
    edge_pct DOUBLE PRECISION, confidence DOUBLE PRECISION, recommendation TEXT,
    rule_profile TEXT, rule_checks_json TEXT, captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_availability_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER NOT NULL, team_name TEXT, injured_count INTEGER DEFAULT 0,
    injured_hitters INTEGER DEFAULT 0, injured_pitchers INTEGER DEFAULT 0,
    injuries_json TEXT, captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS game_context_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(game_id),
    away_lineup_status TEXT, home_lineup_status TEXT,
    away_lineup_json TEXT, home_lineup_json TEXT,
    away_injury_count INTEGER DEFAULT 0, home_injury_count INTEGER DEFAULT 0,
    away_injured_hitters INTEGER DEFAULT 0, home_injured_hitters INTEGER DEFAULT 0,
    away_injuries_json TEXT, home_injuries_json TEXT,
    away_bullpen_pitches_1d INTEGER DEFAULT 0, home_bullpen_pitches_1d INTEGER DEFAULT 0,
    away_bullpen_pitches_3d INTEGER DEFAULT 0, home_bullpen_pitches_3d INTEGER DEFAULT 0,
    away_bullpen_status TEXT, home_bullpen_status TEXT,
    pitcher_change_detected BOOLEAN DEFAULT FALSE, pitcher_change_details TEXT,
    weather_risk_level TEXT, captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS retrosheet_games (
    retro_game_id TEXT PRIMARY KEY, season INTEGER NOT NULL, game_date TEXT NOT NULL,
    away_team TEXT NOT NULL, home_team TEXT NOT NULL, away_score INTEGER NOT NULL,
    home_score INTEGER NOT NULL, winner TEXT, game_type TEXT,
    imported_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS retrosheet_backtests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retro_game_id TEXT NOT NULL REFERENCES retrosheet_games(retro_game_id),
    season INTEGER NOT NULL, model_version TEXT NOT NULL,
    predicted_home_probability DOUBLE PRECISION NOT NULL, predicted_side TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL, actual_winner TEXT NOT NULL,
    correct BOOLEAN NOT NULL, brier_score DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prediction_history_game_time ON model_prediction_history(game_id, captured_at);
CREATE INDEX IF NOT EXISTS idx_game_context_history_game_time ON game_context_snapshots(game_id, captured_at);
CREATE INDEX IF NOT EXISTS idx_live_odds_history_matchup ON live_odds_snapshots(market, away_team, home_team, captured_at);
CREATE INDEX IF NOT EXISTS idx_retrosheet_backtests_season ON retrosheet_backtests(season, model_version);
