-- Supabase / Postgres schema for MLB Edge Dashboard.
-- Paste this into Supabase SQL Editor after creating your project.
-- This mirrors schema.sql but uses Postgres identity columns instead of SQLite AUTOINCREMENT.

CREATE TABLE IF NOT EXISTS games (
    game_id TEXT PRIMARY KEY,
    game_date TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_team TEXT NOT NULL,
    venue_name TEXT,
    venue_lat DOUBLE PRECISION,
    venue_lon DOUBLE PRECISION,
    away_probable_pitcher TEXT,
    home_probable_pitcher TEXT,
    status TEXT,
    status_state TEXT,
    status_code TEXT,
    away_score INTEGER,
    home_score INTEGER,
    inning_state TEXT,
    current_inning TEXT,
    score_summary TEXT,
    box_score_summary TEXT,
    first_pitch_utc TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS odds_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(game_id),
    bookmaker TEXT,
    market TEXT NOT NULL,
    away_price INTEGER,
    home_price INTEGER,
    total_points DOUBLE PRECISION,
    over_price INTEGER,
    under_price INTEGER,
    captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS model_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(game_id),
    run_date TEXT NOT NULL,
    recommended_side TEXT,
    best_market TEXT,
    fair_line INTEGER,
    market_line INTEGER,
    edge_pct DOUBLE PRECISION,
    confidence DOUBLE PRECISION,
    pitching_score DOUBLE PRECISION,
    bullpen_score DOUBLE PRECISION,
    offense_score DOUBLE PRECISION,
    lineup_score DOUBLE PRECISION,
    weather_score DOUBLE PRECISION,
    situation_score DOUBLE PRECISION,
    total_score DOUBLE PRECISION,
    recommendation TEXT,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bet_date TEXT NOT NULL,
    game_id TEXT REFERENCES games(game_id),
    bet_label TEXT NOT NULL,
    market TEXT NOT NULL,
    odds INTEGER NOT NULL,
    stake_units DOUBLE PRECISION NOT NULL,
    result TEXT DEFAULT 'OPEN',
    profit_loss_units DOUBLE PRECISION DEFAULT 0,
    closing_line INTEGER,
    clv_cents INTEGER,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS refresh_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refresh_started_at TEXT NOT NULL,
    refresh_completed_at TEXT,
    status TEXT NOT NULL,
    games_loaded INTEGER DEFAULT 0,
    odds_loaded INTEGER DEFAULT 0,
    weather_loaded INTEGER DEFAULT 0,
    errors TEXT
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS live_odds_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    commence_time TEXT,
    away_team TEXT,
    home_team TEXT,
    bookmaker TEXT,
    market TEXT NOT NULL,
    outcomes_json TEXT NOT NULL,
    captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS weather_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(game_id),
    venue_name TEXT,
    forecast_time TEXT,
    temperature_f DOUBLE PRECISION,
    wind_speed_mph DOUBLE PRECISION,
    wind_direction_deg DOUBLE PRECISION,
    precipitation_probability DOUBLE PRECISION,
    weather_summary TEXT,
    captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_statcast_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team TEXT NOT NULL,
    team_abbr TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    plate_appearances INTEGER DEFAULT 0,
    pitches_seen INTEGER DEFAULT 0,
    xwoba_for DOUBLE PRECISION,
    woba_for DOUBLE PRECISION,
    hard_hit_pct_for DOUBLE PRECISION,
    barrel_pct_for DOUBLE PRECISION,
    k_pct_for DOUBLE PRECISION,
    bb_pct_for DOUBLE PRECISION,
    xwoba_allowed DOUBLE PRECISION,
    woba_allowed DOUBLE PRECISION,
    hard_hit_pct_allowed DOUBLE PRECISION,
    barrel_pct_allowed DOUBLE PRECISION,
    k_pct_pitching DOUBLE PRECISION,
    bb_pct_pitching DOUBLE PRECISION,
    offense_score DOUBLE PRECISION,
    pitching_score DOUBLE PRECISION,
    confluence_score DOUBLE PRECISION,
    captured_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_model_recommendations_run_date ON model_recommendations(run_date);
CREATE INDEX IF NOT EXISTS idx_weather_snapshots_game_id ON weather_snapshots(game_id);
CREATE INDEX IF NOT EXISTS idx_live_odds_snapshots_market_matchup ON live_odds_snapshots(market, away_team, home_team);
CREATE INDEX IF NOT EXISTS idx_team_statcast_metrics_team ON team_statcast_metrics(team);

INSERT INTO settings (key, value)
VALUES
    ('edge_threshold', '4.0'),
    ('min_line_difference_cents', '15'),
    ('min_confidence', '7.0'),
    ('default_stake_units', '1.0'),
    ('bankroll_units', '100'),
    ('bookmaker_preference', 'DraftKings'),
    ('statcast_lookback_days', '14'),
    ('rule_profile', 'Conservative'),
    ('use_manual_rules', 'false'),
    ('dashboard_title', 'MLB Edge Model'),
    ('dashboard_logo_path', 'data/branding/mlb_edge_logo_default.png'),
    ('dashboard_password', '')
ON CONFLICT (key) DO NOTHING;
